# =============================================================================
# Google Play Store Deployment Workflow
# =============================================================================
#
# This is a reusable workflow template for automated Play Store deployments.
# Copy this file to your project's .github/workflows/ directory and customize.
#
# REQUIRED CUSTOMIZATION:
# 1. Replace YOUR_GCP_PROJECT_NUMBER with your Google Cloud project number
# 2. Replace YOUR_GCP_PROJECT_ID with your Google Cloud project ID
# 3. Replace YOUR_PACKAGE_NAME with your app's package name
# 4. Update the build task if using different flavors (e.g., bundleRelease)
# 5. Update the AAB path to match your build output
#
# REQUIRED GITHUB SECRETS:
# - KEYSTORE_FILE_BASE64: Base64 encoded keystore file
# - KEYSTORE_KEY_ALIAS: Key alias from keystore
# - KEYSTORE_STORE_PASSWORD: Keystore password
# - KEYSTORE_KEY_PASSWORD: Key password
# - GOOGLE_SERVICES_JSON_BASE64: Base64 encoded google-services.json (if using Firebase)
#
# REQUIRED SETUP:
# - See google-cloud-setup.md for GCP configuration
# - See google-play-console-setup.md for Play Console permissions
# =============================================================================

name: Deploy to Google Play Store

on:
  # Weekly schedule: Every Monday at 10:00 AM UTC
  schedule:
    - cron: '0 10 * * 1'

  # Manual trigger for ad-hoc deployments
  workflow_dispatch:
    inputs:
      version_suffix:
        description: 'Version suffix (optional, for same-day deploys)'
        required: false
        default: ''
      skip_review:
        description: 'Skip automatic review submission (use after app rejection)'
        required: false
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Generate version numbers
        id: version
        run: |
          # Always use YYMMDDHH format (8 digits)
          # Custom suffix can override the hour if provided
          if [ -n "${{ github.event.inputs.version_suffix }}" ]; then
            VERSION_CODE=$(date +'%y%m%d')${{ github.event.inputs.version_suffix }}
          else
            VERSION_CODE=$(date +'%y%m%d%H')
          fi

          VERSION_NAME="1.${VERSION_CODE}"

          echo "VERSION_CODE=${VERSION_CODE}" >> $GITHUB_ENV
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV
          echo "::notice::Generated versionCode: ${VERSION_CODE}, versionName: ${VERSION_NAME}"

      - name: Restore keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > keystore.jks
          chmod 600 keystore.jks

          # Create keystore.properties for build
          cat > keystore.properties <<EOF
          keyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}
          storePassword=${{ secrets.KEYSTORE_STORE_PASSWORD }}
          keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}
          storeFile=../keystore.jks
          EOF

      # Uncomment if using Firebase (google-services.json)
      # - name: Create google-services.json
      #   env:
      #     GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
      #   run: |
      #     printf '%s' "$GOOGLE_SERVICES_JSON_BASE64" | base64 --decode > app/google-services.json
      #     echo "google-services.json created in app/ directory."

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          # TODO: Replace with your Workload Identity Provider
          # Format: projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_NAME/providers/PROVIDER_NAME
          workload_identity_provider: 'projects/YOUR_GCP_PROJECT_NUMBER/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          # TODO: Replace with your service account email
          service_account: 'github-actions-deploy@YOUR_GCP_PROJECT_ID.iam.gserviceaccount.com'
          create_credentials_file: true
          export_environment_variables: true

      - name: Build app AAB
        run: |
          # TODO: Update the Gradle task to match your build variant
          # Examples:
          #   :app:bundleRelease           - Default release build
          #   :app:bundleNightlyRelease    - Nightly flavor release
          #   :app:bundleProdRelease       - Prod flavor release
          ./gradlew :app:bundleRelease \
            -PversionCode=$VERSION_CODE \
            -PversionName=$VERSION_NAME \
            --no-daemon \
            --stacktrace

      - name: Upload app to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          # TODO: Replace with your app's package name
          packageName: YOUR_PACKAGE_NAME
          # TODO: Update path to match your build output
          # Examples:
          #   app/build/outputs/bundle/release/app-release.aab
          #   app/build/outputs/bundle/nightlyRelease/app-nightly-release.aab
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          # Track options: internal, alpha, beta, production
          # For Wear OS: wear:alpha, wear:production, etc.
          track: alpha
          status: completed
          whatsNewDirectory: .github/whatsnew
          changesNotSentForReview: ${{ github.event.inputs.skip_review == 'true' }}

      - name: Cleanup sensitive files
        if: always()
        run: |
          rm -f keystore.jks keystore.properties app/google-services.json
          rm -f gha-creds-*.json

      - name: Upload build artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs-${{ env.VERSION_CODE }}
          path: app/build/outputs/
          retention-days: 7
